### Creating Numpy Arrays

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.ones and np.zeros
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((2,4))

array([[0.06356147, 0.89834202, 0.8769673 , 0.31733306],
       [0.40288007, 0.96346438, 0.62579726, 0.02252063]])

In [ ]:
# np.linspace
np.linspace(-20,20,7,dtype=int)

array([-20, -14,  -7,   0,   6,  13,  20])

In [ ]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a1
a2 = np.arange(12,dtype=float).reshape(3,4)
a2
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# no. of dimensions
a3.ndim

3

In [ ]:
print(a2.shape)
a2.size

(3, 4)


12

In [ ]:
a3.itemsize

8

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 ==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1

array([[0.83541842, 0.11461032, 0.32885624],
       [0.94480996, 0.28687216, 0.16270456],
       [0.17005699, 0.99196645, 0.03084944]])

In [ ]:
a1 = np.round(a1*100)
a1

array([[84., 11., 33.],
       [94., 29., 16.],
       [17., 99.,  3.]])

In [ ]:
# min/max/sum/prod
# 0 = col and 1 = row in axis
np.prod(a1,axis=0)

array([134232.,  31581.,   1584.])

In [ ]:
np.sum(a1,axis=1)

array([128., 139., 119.])

In [ ]:
np.min(a1,axis=0)

array([17., 11.,  3.])

In [ ]:
np.max(a1,axis=1)

array([84., 94., 99.])

In [ ]:
# mean/median/std/var

np.mean(a1,axis=0)
np.var(a1,axis=1)

array([ 934.88888889, 1164.22222222, 1792.88888889])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.73319032, -0.99999021,  0.99991186],
       [-0.24525199, -0.66363388, -0.28790332],
       [-0.96139749, -0.99920683,  0.14112001]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[3.02507732e+36, 5.98741417e+04, 2.14643580e+14],
       [6.66317622e+40, 3.93133430e+12, 8.88611052e+06],
       [2.41549528e+07, 9.88903032e+42, 2.00855369e+01]])

In [ ]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[79., 33., 65.],
       [62.,  5., 97.]])

In [ ]:
np.floor(np.random.random((3,4))*100)

array([[42.,  6., 77., 98.],
       [55., 38., 94.,  7.],
       [95., 69., 69., 47.]])

In [ ]:
np.ceil(np.random.random((3,4))*100)

array([[40., 57., 70., 20.],
       [95., 65., 78., 83.],
       [34., 43., 32., 11.]])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,2]

2

In [ ]:
a3[1,0,1]

5

In [ ]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:8:2]

array([2, 4, 6])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1:2]

array([[1],
       [5]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:

a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping



In [ ]:
# Transpose
np.transpose(a2)


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
np.ravel(a3) # for convert M dim arry in single D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]