### np.sort

Return a sorted copy of an array.


In [ ]:
import numpy as np

a = np.random.randint(0,100,15)
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.sort(a)[::-1]

array([86, 81, 67, 63, 61, 54, 52, 51, 48, 41, 33, 24, 22, 11,  0])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b
np.sort(b,axis=0)

array([[12,  5,  4,  4],
       [14,  7, 12,  8],
       [26, 41, 28, 36],
       [31, 56, 40, 69],
       [32, 76, 53, 89],
       [44, 89, 64, 94]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [ ]:
np.append(a,200)

array([ 52,  33,  81,  22,  41,  61,  54,  86,  63,  11,  48,   0,  51,
        24,  67, 200])

In [ ]:
b

array([[31,  5, 53, 89],
       [26, 56, 28, 36],
       [14, 76, 40, 69],
       [12,  7, 64,  4],
       [32, 89,  4,  8],
       [44, 41, 12, 94]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[31.        ,  5.        , 53.        , 89.        ,  0.61577153],
       [26.        , 56.        , 28.        , 36.        ,  0.17450565],
       [14.        , 76.        , 40.        , 69.        ,  0.32740954],
       [12.        ,  7.        , 64.        ,  4.        ,  0.81703614],
       [32.        , 89.        ,  4.        ,  8.        ,  0.15743243],
       [44.        , 41.        , 12.        , 94.        ,  0.1970739 ]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.



In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.



In [ ]:
e = np.array([1,2,3,4,54,3,2,234,23,23,21,2,21,1,1,2,3,4,5,6,])

np.unique(e)

array([  1,   2,   3,   4,   5,   6,  21,  23,  54, 234])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

In [ ]:
a.shape
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [ ]:
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.where(a>50)

(array([ 0,  2,  5,  6,  7,  8, 12, 14]),)

In [ ]:
# replace all values > 50 with 0
# np.where(condi,true,false)
np.where(a>50,0,a)

array([ 0, 33,  0, 22, 41,  0,  0,  0,  0, 11, 48,  0,  0, 24,  0])

In [ ]:
np.where(a%2==0,0,a)

array([ 0, 33, 81,  0, 41, 61,  0,  0, 63, 11,  0,  0, 51,  0, 67])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [ ]:
np.argmax(a)

7

In [ ]:
np.argmax(b,axis=1)

array([3, 1, 1, 2, 1, 3])

In [ ]:
# np.argmin
np.argmin(a)

11

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [ ]:
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.cumsum(a)

array([ 52,  85, 166, 188, 229, 290, 344, 430, 493, 504, 552, 552, 603,
       627, 694])

In [ ]:
np.cumsum(b,axis=1)

array([[ 31,  36,  89, 178],
       [ 26,  82, 110, 146],
       [ 14,  90, 130, 199],
       [ 12,  19,  83,  87],
       [ 32, 121, 125, 133],
       [ 44,  85,  97, 191]])

In [ ]:
np.cumsum(b)

array([ 31,  36,  89, 178, 204, 260, 288, 324, 338, 414, 454, 523, 535,
       542, 606, 610, 642, 731, 735, 743, 787, 828, 840, 934])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                 52,                1716,              138996,
                   3057912,           125374392,          7647837912,
              412983247248,      35516559263328,    2237543233589664,
         24612975569486304, 1181422827335342592,                   0,
                         0,                   0,                   0])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.


In [ ]:
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.percentile(a,20)

23.6

In [ ]:
np.median(a)

51.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

In [ ]:
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 2, 1, 2, 3, 3, 0, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
exp = np.array([1,3,2,4,2])

np.corrcoef(salary,exp)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [ ]:
item = [10,20,30,40,50,60,70,80,90]

np.isin(a,item)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [ ]:
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.flip(a)

array([67, 24, 51,  0, 48, 11, 63, 86, 54, 61, 41, 22, 81, 33, 52])

In [ ]:
b

array([[31,  5, 53, 89],
       [26, 56, 28, 36],
       [14, 76, 40, 69],
       [12,  7, 64,  4],
       [32, 89,  4,  8],
       [44, 41, 12, 94]])

In [ ]:
np.flip(b)

array([[94, 12, 41, 44],
       [ 8,  4, 89, 32],
       [ 4, 64,  7, 12],
       [69, 40, 76, 14],
       [36, 28, 56, 26],
       [89, 53,  5, 31]])

In [ ]:
np.flip(b,axis=1)

array([[89, 53,  5, 31],
       [36, 28, 56, 26],
       [69, 40, 76, 14],
       [ 4, 64,  7, 12],
       [ 8,  4, 89, 32],
       [94, 12, 41, 44]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

In [ ]:
a

array([52, 33, 81, 22, 41, 61, 54, 86, 63, 11, 48,  0, 51, 24, 67])

In [ ]:
np.put(a,[0,1],[110,530])

In [ ]:
a

array([110, 530,  81,  22,  41,  61,  54,  86,  63,  11,  48,   0,  51,
        24,  67])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [ ]:
a

array([110, 530,  81,  22,  41,  61,  54,  86,  63,  11,  48,   0,  51,
        24,  67])

In [ ]:
np.delete(a,2)

array([110, 530,  22,  41,  61,  54,  86,  63,  11,  48,   0,  51,  24,
        67])

In [ ]:
np.delete(a,[0,2,4])

array([530,  22,  61,  54,  86,  63,  11,  48,   0,  51,  24,  67])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

In [ ]:
a

array([110, 530,  81,  22,  41,  61,  54,  86,  63,  11,  48,   0,  51,
        24,  67])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 41, 61, 54, 75, 63, 25, 48, 25, 51, 25, 67])