In [3]:
### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
# Filling the numpy array with NaN values
a = np.empty(10)*np.nan
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [14]:
### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))
x = np.random.random((a,b))
print(x)
print("Average of the array elements is: ",x.mean())


Enter the value of a: 4
Enter the value of b: 6
[[0.34942408 0.57429338 0.61855872 0.79363987 0.15714784 0.72121407]
 [0.02768525 0.96080067 0.73212488 0.99373695 0.33430387 0.13764747]
 [0.95296664 0.55827324 0.48271944 0.91609204 0.89689231 0.69277029]
 [0.76492377 0.25762393 0.03205014 0.78690153 0.41068721 0.69621532]]
Average of the array elements is:  0.5770288711317058


In [16]:
### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

# Eg.-
# ```
# [[1,1,1,1],
# [1,0,0,1],
# [1,0,0,1],
# [1,1,1,1]]
# ```

def borderarray(a,b):
  x = np.ones((a,b))
  x[1:-1,1:-1] = 0
  return x

borderarray(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.

np.linspace(0,1,12)[1:-1]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [23]:
#Code here
# Identity matricx is a square mattrix, means no of rows and columns will always be same.
# Here shape given 3,4 so identuty matrix not possible.

#Identy matrix of size 3-- 3X3
np.eye(3)

#Identy matrix of size 4-- 4X4
np.identity(4)

# eye and identity are same.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

z = np.zeros((5,5))
z
z= z + np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [40]:
# ### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates,
# and coordinates of a point as array is given. Create an array of distance of each point in the random vectros
# from the given point. Distance array should be interger type.

# ```
point = np.array([2,3])
# ```


x = np.random.randint(1,100,(10,2))

np.sqrt(np.sum((x-point)**2,axis=1)).astype(int)

array([ 85,  53,  79,  67,  10,  38, 105,  75,  96,  58])

In [43]:
### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [47]:
a = input().strip().split()
a = np.array(a[::-1],dtype=np.float32)
a

2 43 45 65 76 


array([76., 65., 45., 43.,  2.], dtype=float32)

In [48]:
a = np.zeros((2,3))
a.size

6

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

In [49]:
def softmax(arr):
  if type(arr)!=np.ndarray:
    raise TypeError("Enter a numpy array")
  elif arr.ndim>1:
    raise TypeError("Enter a 1D array")
  s = np.sum(np.exp(arr))
  return np.exp(arr)/s

softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))


array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



In [50]:
def v_stack(*args):
  for i in args:
    if type(i)!=np.ndarray:
      raise TypeError("Enter a numpy array")

    return np.vstack(args)

v_stack(np.array([1,2,3]),np.array([4,5,6]),np.array([7,8,9]))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
c= np.random.random((2,5))

print(v_stack(a,b,c))

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.28944001 0.97127917 0.65116211 0.49329523 0.86539619]
 [0.61371358 0.87887183 0.54550006 0.41958072 0.13474652]]


In [58]:
x = np.random.random((5,4))
x - x.mean(axis = 1, keepdims = True)

array([[-0.49236189,  0.44053129, -0.15633244,  0.20816304],
       [-0.28464819, -0.32916663,  0.19696719,  0.41684763],
       [ 0.28970967, -0.19353441,  0.1446394 , -0.24081466],
       [ 0.28027253, -0.14381878, -0.14761965,  0.01116589],
       [ 0.24735121, -0.28012167, -0.316145  ,  0.34891546]])

In [60]:
### `Q-15:` Swap column-1 of array with column-2 in the array.
a = np.arange(9).reshape(3,3)
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [61]:
### `Q-16:` Replace odd elements in arrays with -1.
a = np.arange(10)
a[a%2!=0] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [64]:
# Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
a = np.array([1,32,4,2,5,6])
b = np.array([4,2,54,45,2,34])
a[b>a] = b[a<b]
a

array([ 4, 32, 54, 45,  5, 34])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array


There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [65]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[6439, 4769,  198,   18, 1868],
       [9613, 3398, 8249, 3329, 7711],
       [2591, 3801, 4713, 9722, 7585],
       [8867, 7892, 8823, 9830, 7613],
       [1017, 5747, 6362, 5702, 2312],
       [5798, 1249, 1687, 3804, 7303],
       [1606, 1629, 9749, 3753, 9628],
       [8444, 5750, 5456, 6443, 8439]])

In [66]:
arr1[:,::2]

array([[6439,  198, 1868],
       [9613, 8249, 7711],
       [2591, 4713, 7585],
       [8867, 8823, 7613],
       [1017, 6362, 2312],
       [5798, 1687, 7303],
       [1606, 9749, 9628],
       [8444, 5456, 8439]])

In [68]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.65440277, 0.48420302, 0.01834488, 0.        , 0.18854464],
       [0.97788422, 0.34447615, 0.83887077, 0.33744395, 0.78403995],
       [0.26222992, 0.38554831, 0.47849572, 0.98899307, 0.77119853],
       [0.90185487, 0.80248675, 0.89737057, 1.        , 0.77405218],
       [0.10181411, 0.58387689, 0.64655524, 0.57929066, 0.23379535],
       [0.5890746 , 0.12545862, 0.17009784, 0.38585406, 0.74245821],
       [0.16184264, 0.16418671, 0.9917448 , 0.38065634, 0.97941296],
       [0.85874439, 0.58418263, 0.55421932, 0.65481044, 0.85823481]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [69]:
#Code here
def nthmax(arr, n):
    if n>len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

34

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [72]:

a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])