Create a random 3x4 matrix with value between 0-100. And perform below tasks

i. Sort this matrix. np.sort()

ii. Sort this matrix based on values in 2nd column.

iii. Sort this matrix based on max value in each row.

iv. Sort based on elements value.

In [2]:
import numpy as np


In [19]:
arr = np.random.randint(0,100,size=(3,4))
print(arr)
print(np.sort(arr))
print(arr[arr[:,1].argsort()])

print(np.array(sorted(arr, key = lambda x: max(x))))
print(np.sort(arr, axis = None).reshape(4,3))

[[12 84  9 62]
 [37 88 97 14]
 [80  5 63 35]]
[[ 9 12 62 84]
 [14 37 88 97]
 [ 5 35 63 80]]
[[80  5 63 35]
 [12 84  9 62]
 [37 88 97 14]]
[[80  5 63 35]
 [12 84  9 62]
 [37 88 97 14]]
[[ 5  9 12]
 [14 35 37]
 [62 63 80]
 [84 88 97]]


There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.

i. Add marks every student of an extra subject in the same array.

ii. Add two new students marks in respective 5 subjects.(one subject added in above task)

iii. Add extra column with sum of all subjects(5-subjects) marks

iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

In [45]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(-1, 1)
marks = np.concatenate([marks, extra_subject], axis = 1)
print(marks)
#2
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1, -1)
rec2 = np.array([92,71,52,61,53]).reshape(1,-1)
marks = np.concatenate([marks, rec1, rec2], axis = 0) 
print(marks)
#3
sum_of_student = marks.sum(axis = 1, keepdims=True)
sum1 = np.concatenate([marks,sum_of_student],axis=1)
print(sum1)
#4 
print(np.array(sorted(marks, key = lambda x: x[-1], reverse=True)))

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]
[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]
[[67 61 59 36 92]
 [77 83 98 95 89]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [92 71 52 61 53]
 [13 10  9 33 41]
 [82  9 29 78 36]]
